export default {
  weight: 'Váha',
  dimension: 'Rozměry',
  material: 'Materiál',
  detail: 'DETAIL',
  order: 'POPTAT',
  optional: 'nepovinné',
  searchLabel: 'Hledat',
  itemsNo: 'Počet kusů',
  length: 'Délka',
  demandForm: {
    errors: {
      name: 'Prosím zadejte své jméno',
      companyName: 'Prosím zadejte název společnosti',
      street: 'Nesprávně zadaná adresa',
      city: 'Nesprávně zadané město',
      postal_code: 'Nesprávně zadané PSČ',
      email: 'Nesprávně zadaný e-mail',
      dic: 'Nesprávně zadaný DIČ',
      ico: 'Nesprávně zadané IČO',
      phone: 'Nesprávně zadané telefonní číslo',
      generic: 'Nesprávně vyplněné pole',
    },
  },
};
